Week 2 assignment
Lidemy/mentor-program-5th-lea6121 pull request #3
Opened 2021-04-21 02:22 UTC by lea6121

完成 week 2 hw1.js, hw2.js, hw3.js, hw4.js, hw5.js 和 hw6.md。

2021-04-21 14:08 UTC, cwc329 requested changes
hw6 有重大錯誤請修正，另外對於迴圈的觀念也沒有講得很清楚，想看看要怎麼表達會比較好。
看程式碼看得出有對變數做有意義的命名，這個不錯。
不過如果要交作業的話建議把沒有用到的程式碼刪除，這樣會比較好閱讀。

2021-04-21 14:08 UTC, cwc329 commented on homeworks/week2/hw2.js
> +  //   console.log(str);
沒有用到的程式碼可以刪掉，
用註解的方式留著會影響閱讀。

2021-04-21 14:08 UTC, cwc329 commented on homeworks/week2/hw3.js
> +  n = n - 1;
這樣建議可以直接`var n = str.length - 1;`
另外建議變數命名再語意化一些，單個字母會不知道這個變數的意義。

2021-04-21 14:08 UTC, cwc329 commented on homeworks/week2/hw4.js
> +      console.log("任何整數都是 0 的因數");
有想到處理 edge case 不錯，不過題目有要印出這個嗎？
另外如果是 edge case，還需要進到迴圈嗎？

2021-04-21 14:08 UTC, cwc329 commented on homeworks/week2/hw5.js
>  }
試試看這組
```
([',,,', ',,,'], '$$')
```

2021-04-21 14:08 UTC, cwc329 commented on homeworks/week2/hw6.md
> +   `變數 i 設定起始值為 0，當 i 小於陣列最大長度即終止 (此陣列長度為 6)，每執行完一次迴圈 i 就加 1`
小於陣列最大長度就終止，那一開始就結束了？

2021-04-21 14:08 UTC, cwc329 commented on homeworks/week2/hw6.md
> +3. 索引值 0 的數字 3 進到 for 迴圈一的 if 判斷式。當索引值代表數字小於等於 0 就回傳 `invalid`。數字 3 沒有小於等於 0，不 return
進到迴圈的是數字 3 嗎？
在這個迴圈裡面到底有什麼東西？
你這樣對迴圈的理解有點奇怪。
用生動的文字敘述是很好沒錯，不過觀念要先釐清。

2021-04-23 02:21 UTC, lea6121 commented
@cwc329 作業訂正完成，再麻煩助教

2021-04-29 13:12 UTC, cwc329 reviewed
抱歉沒有過來看ＱＱ
有訂正給推！

還是有點小錯誤，
一個是用詞上不夠精確，
另一個是對於迴圈結束條件的判斷沒有很熟悉。

修正過後應該就沒有問題了。

2021-04-29 13:12 UTC, cwc329 commented on homeworks/week2/hw6.md
> +   `變數 i 設定起始值為 0； 執行條件：i 小於陣列最大長度 (此陣列長度為 6)； 每執行完一次迴圈 i 就加 1`
應該不是最大長度。

2021-04-29 13:12 UTC, cwc329 commented on homeworks/week2/hw6.md
> +8. i = 5，若 arr[5] 的值小於等於 0 就回傳 `invalid`。數字 35 未小於等於 0，不 return。for 迴圈一結束
迴圈為何會結束？
是在什麼時候結束？

2021-04-29 15:27 UTC, cwc329 approved these changes

2021-04-29 15:27 UTC, merged